# Generated by Django 2.1.1 on 2018-09-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lender_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('checked-out', 'Checked-Out')], default='available', max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.DateField(null=True),
        ),
    ]
